# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#header
    weight: 10
  - name: Posts
    url: /#blog-posts
    weight: 20
  - name: About
    url: /#about
    weight: 30
#  - name: About
#    url: about/
#    weight: 20
#  - name: About
#    url: about/
#    weight: 20
#  - name: About
#    url: about/
#    weight: 20
